version: '3.3'

services:
   database:
     image: mariadb:latest
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: CoreDash
       MYSQL_USER: development
       MYSQL_PASSWORD: password

volumes:
  db_data:
