version: '3'
services:
  app:
    env_file: .env
    restart: unless-stopped
    build:
      context: ./web
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_HASH=${COMPOSER_HASH}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
        - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
    ports:
      - '8888:80'
    volumes:
      - ./web/src:/var/www
      - ./logs/web:/var/www/storage/logs

version: '3.1'
services:
   mysql:
    env_file: .env
    restart: unless-stopped
    build: ./databases/mysql
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./storage/mysql:/var/lib/mysql
      - ./databases/mysql/conf.d:/etc/mysql/conf.d
  webapp:
    build: .
    command: php artisan serve --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    depends_on:
      - db